######################################################################
# Automatically generated by qmake (2.01a) czw. maj 19 23:10:13 2011
######################################################################

TEMPLATE = app
TARGET = tyranny-client 
DEPENDPATH += . src src/ui
INCLUDEPATH += . src

MOC_DIR = moc
UI_DIR = src/ui

# Input
HEADERS += src/mainwindow.h
FORMS += src/ui/mainwindow.ui
SOURCES += src/client.cpp src/mainwindow.cpp
